# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeoSimplification
                                 A QGIS plugin
 This plugin contains different tools for line simplification
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-01-27
        copyright            : (C) 2021 by Daniel Pilon
        email                : daniel.pilon@canada.ca
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Daniel Pilon'
__date__ = '2021-01-27'
__copyright__ = '(C) 2021 by Daniel Pilon'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GeoSimplification class from file GeoSimplification.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .geo_sim_processing import GeoSimplificationPlugin
    return GeoSimplificationPlugin()
